language: node_js
sudo: false
node_js:
  - 9

cache:
  directories:
    - node_modules
    
install:
  - node -e "const peers = Object.entries(require('./package.json').peerDependencies || {}).map(d => d.join('@')).join(' '); console.log('peers', peers); if (peers.length) process.stdout.write('yarn add -P --no-lockfile ' + String(peers));" | sh
  - yarn global add typings
  - typings install

script:
  - yarn transpile

deploy:
  skip_cleanup: true
  provider: npm
  email: olegman.ru@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: router-async/hook-fetcher
