language: node_js
sudo: false
node_js:
  - 9

cache:
  directories:
    - node_modules
    
install:
  - yarn global add jq
  - yarn add -P $(jq -r '.peerDependencies | to_entries | map(\"\\(.key)@\\(.value | tostring)\") | join(\" \")' package.json)
  - yarn global add typings
  - typings install

script:
  - yarn transpile

deploy:
  skip_cleanup: true
  provider: npm
  email: olegman.ru@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: router-async/hook-fetcher
