language: node_js
sudo: false
node_js:
  - 6

before_install:
  - npm install -g npm-install-peers
  - npm-install-peers

script:
  - yarn global add typings
  - typings install
  - yarn transpile

deploy:
  skip_cleanup: true
  provider: npm
  email: olegman.ru@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: router-async/hook-fetcher
