language: node_js
sudo: false
node_js:
  - 9

before_install:
  - node -e "const peers = Object.entries(require('./package.json').peerDependencies || {}).map(d => d.join('@')).join(' '); if (peers.length) process.stdout.write('yarn add -P --no-lockfile ' + String(peers));" | sh

script:
  - yarn global add typings
  - typings install
  - yarn transpile

deploy:
  skip_cleanup: true
  provider: npm
  email: olegman.ru@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: router-async/hook-fetcher
